# Generated by Django 5.2.11 on 2026-02-17 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('State', models.TextField(max_length=40)),
                ('Street_address', models.TextField()),
                ('City', models.CharField(max_length=30)),
                ('Zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
