# Generated by Django 5.2.11 on 2026-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='State',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Street_address',
            field=models.CharField(),
        ),
    ]
