# Generated by Django 5.2.11 on 2026-02-09 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(unique=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, null=True, unique=True, verbose_name='Имя категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Короткая ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BlogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('Slider', models.ImageField(upload_to='blog/slider/', verbose_name='Слайд')),
                ('Short_description', models.CharField(max_length=40, verbose_name='Краткое описание')),
                ('Full_description', models.TextField(verbose_name='полное описание')),
                ('Image', models.ImageField(null=True, upload_to='blog/images/', verbose_name='Фото')),
                ('Slug', models.SlugField(unique=True, verbose_name='Короткая ссылка')),
                ('Author', models.CharField(max_length=20, verbose_name='Автор статьи')),
                ('Tag', models.ManyToManyField(related_name='tags', to='blog.blogtag', verbose_name='Тэг')),
                ('Category', models.ManyToManyField(related_name='categories', to='blog.category', verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Website', models.CharField(null=True)),
                ('Text', models.TextField(null=True, verbose_name='Текст коммента')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogitem', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарии',
            },
        ),
    ]
