# Generated by Django 5.2.11 on 2026-02-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='Category',
            field=models.ManyToManyField(related_name='blog_items', to='blog.category', verbose_name='Имя категории'),
        ),
    ]
