# Generated by Django 5.2.11 on 2026-02-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='email',
        ),
    ]
