# Generated by Django 5.2.11 on 2026-02-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user_favorite_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='email',
            new_name='user',
        ),
    ]
