# Generated by Django 5.2.11 on 2026-02-09 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(verbose_name='Название')),
                ('Slug', models.SlugField(max_length=150, unique=True, verbose_name='Краткая ссылка')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(verbose_name='Название')),
                ('Price', models.CharField(verbose_name='Цена продукта')),
                ('Sale_percent', models.IntegerField(default=0, verbose_name='Процент скидки')),
                ('Preview', models.ImageField(blank=True, null=True, upload_to='shops/preview')),
                ('Slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='RelatedProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(verbose_name='Заголовок')),
                ('Text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(verbose_name='Краткое название')),
                ('Price', models.IntegerField(verbose_name='Цена продукта')),
                ('Preview', models.ImageField(null=True, upload_to='shop/products/preview/', verbose_name='Фото')),
                ('Sale_percent', models.IntegerField(default=0, verbose_name='Процент скидки')),
                ('Short_description', models.TextField()),
                ('Slug', models.SlugField(max_length=150, unique=True, verbose_name='Краткая ссылка')),
                ('Quantity', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('Size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'large'), ('extra_large', 'Extra_large')], null=True, verbose_name='Размер продуктов')),
                ('Status', models.CharField(blank=True, choices=[('sold', 'Sold'), ('new', 'New'), ('in stock', 'In stock')], null=True, verbose_name='Статус продукта')),
                ('Sold', models.IntegerField(default=0, verbose_name='Проданные товары')),
                ('Category', models.ManyToManyField(related_name='categories', to='shop.category')),
            ],
            options={
                'verbose_name': 'Страница продукта',
                'verbose_name_plural': 'Страницы продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='shop/images/', verbose_name='Фото продукта')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='заголовок', to='shop.product')),
            ],
            options={
                'verbose_name': 'Фото продукта',
            },
        ),
    ]
