# Generated by Django 5.2.11 on 2026-02-09 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Subtitle', models.CharField(max_length=30, verbose_name='Текст до заголовка')),
                ('Title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('Text', models.CharField(max_length=40, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=30, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview', models.ImageField(upload_to='slider/', verbose_name='Фото главной страницы')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('short_description', models.TextField(max_length=50, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='InstagramPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Subtitle', models.CharField(max_length=30, verbose_name='Текст до заголовка')),
                ('Title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='instagram_photo/', verbose_name='Фото')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='slider/icon/', verbose_name='Иконка')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=30, verbose_name='Краткое описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('Text', models.CharField(max_length=40, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст до слайда',
                'verbose_name_plural': 'Текст до слайдов',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photo', verbose_name='Фото автора')),
                ('text', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('position', models.CharField(max_length=10, verbose_name='Текущая позиция')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
